# ======================================================
# CPC Training Configuration for ESC-50
# ======================================================

# -------- Global constants --------
seed: 42
batch_size: 512
target_sr: 16000
chunk_sec: 1.0
overlap: 0.5
signal_threshold: 0.05
num_workers: 16
epochs: 15
disable_wandb: false
data_path: "/root/synthetic_dataset/2-5"

# -------- Run & logging --------
wandb_project: "cpc-syn"
wandb_entity: null
run_name: "GN-LN_nopadding"

# -------- Paths --------
paths:
  train_dataset_dir: "${data_path}/train"
  val_dataset_dir: "${data_path}/val"
  test_dataset_dir: "${data_path}/test"
  checkpoint_dir: "checkpoints/GN-LN"

# -------- Trainer --------
trainer:
  accelerator: "gpu"
  max_epochs: ${epochs}
  precision: 32
  num_sanity_val_steps: 1
  enable_checkpointing: true

# -------- Model --------
model:
  tau: 0.07
  timestep: 12

# -------- Data --------
data:
  train_dataset_dir: ${paths.train_dataset_dir}
  val_dataset_dir: ${paths.val_dataset_dir}
  test_dataset_dir: ${paths.test_dataset_dir}
  batch_size: ${batch_size}
  num_workers: ${num_workers}
  seed: ${seed}
  target_sr: ${target_sr}
  chunk_sec: ${chunk_sec}
  overlap: ${overlap}
  signal_threshold: ${signal_threshold}

# -------- Optimization --------
optim:
  optimizer:
    type: "AdamW"
    lr: 1e-4
    betas: [0.9, 0.98]
    eps: 1e-9
    weight_decay: 1e-5

  scheduler:
    type: "LinearWarmupCosineAnnealingLR"
    warmup_steps: 4000
    max_steps: 100000
    warmup_start_lr: 0.0
    eta_min: 1e-6

  interval: "step"
  frequency: 1
