# ======================================================
# CPC Training Configuration for ESC-50
# ======================================================

# -------- Global constants --------
seed: 42
batch_size: 512
target_sr: 16000
window_sec: 1.0
hop_sec: 0.5
num_workers: 16
epochs: 15
disable_wandb: false
data_path: "/Users/zhanghaodong/Desktop/ESC-50-master"

# -------- Run & logging --------
wandb_project: "cpc-esc-50"
wandb_entity: null
run_name: "cdck2-stable-pretraining"

# -------- Paths --------
paths:
  audio_dir_path: "${data_path}/audio"
  meta_csv_path: "${data_path}/meta/esc50.csv"
  checkpoint_dir: "./checkpoints"

# -------- Trainer --------
trainer:
  accelerator: "cpu"
  max_epochs: ${epochs}
  precision: 32
  num_sanity_val_steps: 1
  enable_checkpointing: true

# -------- Model --------
model:
  tau: 0.07
  timestep: 12

# -------- Data --------
data:
  meta_csv_path: ${paths.meta_csv_path}
  audio_dir_path: ${paths.audio_dir_path}
  batch_size: ${batch_size}
  num_workers: ${num_workers}
  seed: ${seed}
  target_sr: ${target_sr}
  window_sec: ${window_sec}
  hop_sec: ${hop_sec}

# -------- Optimization --------
optim:
  optimizer:
    type: "AdamW"
    lr: 1e-4
    betas: [0.9, 0.98]
    eps: 1e-9
    weight_decay: 1e-5

  scheduler:
    type: "LinearWarmupCosineAnnealingLR"
    warmup_steps: 4000
    max_steps: 100000
    warmup_start_lr: 0.0
    eta_min: 1e-6

  interval: "step"
  frequency: 1
